apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-cdp-volumes-customizer-cfg
  annotations:
    cert-manager.io/inject-ca-from: cdp-customizer/volumes-webhook-cert
  labels:
    app: cdp-volumes-customizer
webhooks:
  - name: mutating-cdp-volumes-console.datacreating.com
    clientConfig:
      service:
        name: volumes-admission-manager
        namespace: cdp-customizer
        path: "/mutate"
    rules:
      - operations: ["CREATE"]
        apiGroups: ["apps","batch"]
        apiVersions: ["v1"]
        resources: ["deployments","statefulsets","jobs"]
    namespaceSelector:
      matchExpressions:
        # key exist
        - key: monitoring-platform-access
          operator: Exists
    timeoutSeconds: 5
  - name: mutating-cdp-volumes-cml.datacreating.com
    clientConfig:
      service:
        name: volumes-admission-manager
        namespace: cdp-customizer
        path: "/mutate"
    rules:
      - operations: ["CREATE"]
        apiGroups: ["apps","batch"]
        apiVersions: ["v1"]
        resources: ["deployments","statefulsets","jobs"]
    namespaceSelector:
      matchExpressions:
        # key exist
        - key: associatedCRP
          operator: Exists
    timeoutSeconds: 5
  - name: mutating-cdp-volumes-implala.datacreating.com
    clientConfig:
      service:
        name: volumes-admission-manager
        namespace: cdp-customizer
        path: "/mutate"
    rules:
      - operations: ["CREATE"]
        apiGroups: ["apps","batch"]
        apiVersions: ["v1"]
        resources: ["deployments","statefulsets","jobs"]
    namespaceSelector:
      matchExpressions:
        # key exist
        - key: istio-injection
          operator: Exists
    timeoutSeconds: 5
  - name: mutating-cdp-volumes-monitoring.datacreating.com
    clientConfig:
      service:
        name: volumes-admission-manager
        namespace: cdp-customizer
        path: "/mutate"
    rules:
      - operations: ["CREATE"]
        apiGroups: ["apps","batch"]
        apiVersions: ["v1"]
        resources: ["deployments","statefulsets","jobs"]
    namespaceSelector:
      matchExpressions:
        # key exist
        - key: cdp.cloudera/version
          operator: Exists
    timeoutSeconds: 5