apiVersion: v1
kind: Service
metadata:
  name: volumes-admission-manager
  labels:
    app: cdp-volumes-customizer
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: cdp-volumes-customizer
